// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOaYq8x5dBLWhOtR9RQpmmlQnK8p_caF4',
    appId: '1:373727421748:web:022d362c7ef05dc3617161',
    messagingSenderId: '373727421748',
    projectId: 'database-tester-leng',
    authDomain: 'database-tester-leng.firebaseapp.com',
    storageBucket: 'database-tester-leng.firebasestorage.app',
    measurementId: 'G-KK76E1XDQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Nq-V-6glpX7OKVRyAsOEshAh7nML810',
    appId: '1:373727421748:android:b38e5dc2ff7f51ab617161',
    messagingSenderId: '373727421748',
    projectId: 'database-tester-leng',
    storageBucket: 'database-tester-leng.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOaYq8x5dBLWhOtR9RQpmmlQnK8p_caF4',
    appId: '1:373727421748:web:e917e7c5af8d50b1617161',
    messagingSenderId: '373727421748',
    projectId: 'database-tester-leng',
    authDomain: 'database-tester-leng.firebaseapp.com',
    storageBucket: 'database-tester-leng.firebasestorage.app',
    measurementId: 'G-VWRCQ7X4MQ',
  );
}
